name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: my welcome message
          run: echo "my first run!!"
        - name: Checkout
          uses: actions/checkout@v6.0.2
        - name: List files
          run: ls -a
        - name: Read readme
          run: cat README.md     
    Second_job:
        runs-on: ubuntu-latest
        needs: first_job  
        steps:
        - name: external package
          run: sudo apt install -y cowsay 
        - name: create dragon
          run: cowsay -f dragon "I am the real king of the jungle !!!" >> dragon.txt
        - name: run everything
          run: |
            echo "list the files"
            ls -Ral
        - name: read file
          run: cat dragon.txt
    Third_job:
        runs-on: ubuntu-latest
        needs: Second_job
        steps:
        - name: make shell script executable
          run: chmod +x ascii_script.sh
        - name: executing shell script
          run: ./ascii_script.sh





