name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: my welcome message
          run: echo "my first run!!"
        - name: Checkout
          uses: actions/checkout@v6.0.2
        - name: List files
          run: ls -a
        - name: Read readme
          run: cat README.md       
        - name: external package
          run: sudo apt install -y cowsay 
        - name: create dragon
          run: cowsay -f dragon "I am the real king of the jungle !!!" >> dragon.txt
        - name: run everything
          run: |
            echo "list the files"
            ls -Ral
        - name: check file exists
          run: grep -i "dragon" dragon.txt
        - name: read file
          run: cat dragon.txt 





