name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: my welcome message
          run: echo "my first run!!"
        - name: Checkout
          uses: actions/checkout@v6.0.2
        - name: List files
          run: ls -a
        - name: Read readme
          run: cat README.md


